language: scala
scala:
  - 2.11.12
  - 2.12.8
jdk:
  - openjdk8
  - openjdk11
cache:
  directories:
    - $HOME/.ivy2/cache
script:
  - sbt ++$TRAVIS_SCALA_VERSION coverage convertJVM/test convertJS/test
after_success:
  - sbt ++$TRAVIS_SCALA_VERSION convertJVM/coverageReport convertJS/coverageReport coverageAggregate coveralls
