language: scala
scala:
  - 2.11.12
  - 2.12.8
  - 2.13.0-RC3
jdk:
  - openjdk8
  - openjdk11
cache:
  directories:
    - $HOME/.ivy2/cache
script:
  - sbt ++$TRAVIS_SCALA_VERSION coverage test
after_success:
  - sbt ++$TRAVIS_SCALA_VERSION coverageReport  coverageAggregate coveralls
