language: scala
scala:
  - 2.11.8
  - 2.11.11
  - 2.11.12
  - 2.12.0
  - 2.12.1
  - 2.12.2
  - 2.12.3
  - 2.12.4
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.ivy2/cache
script:
  - sbt ++$TRAVIS_SCALA_VERSION coverage convertJVM/test convertJS/test
after_success:
  - sbt ++$TRAVIS_SCALA_VERSION convertJVM/coverageReport convertJS/coverageReport coverageAggregate coveralls
